/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inventario_ListaDoble;

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Modificar_articulo extends javax.swing.JFrame {
    private String codigoSeleccionado;
    private String nombreSeleccionado;
    private String descripcionSeleccionado;
    private int unidadesSeleccionado;
    private double precioSeleccionado;

    private boolean nombreBloqueado = false;
    private boolean unidadesBloqueadas = false;
    private boolean precioBloqueado = false;
    private boolean descripcionBloqueada = false;

    public String getNombreSeleccionado() {
        return nombreSeleccionado;
    }

    public void setNombreSeleccionado(String nombreSeleccionado) {
        this.nombreSeleccionado = nombreSeleccionado;
    }

    public String getDescripcionSeleccionado() {
        return descripcionSeleccionado;
    }

    public void setDescripcionSeleccionado(String descripcionSeleccionado) {
        this.descripcionSeleccionado = descripcionSeleccionado;
    }

    public int getUnidadesSeleccionado() {
        return unidadesSeleccionado;
    }

    public void setUnidadesSeleccionado(int unidadesSeleccionado) {
        this.unidadesSeleccionado = unidadesSeleccionado;
    }

    public double getPrecioSeleccionado() {
        return precioSeleccionado;
    }

    public void setPrecioSeleccionado(double precioSeleccionado) {
        this.precioSeleccionado = precioSeleccionado;
    }
    
    /**
     * Creates new form Modificar_articulo
     */
    public Modificar_articulo() {
        initComponents();
    }
    public String getCodigoSeleccionado() {
        return codigoSeleccionado;
    }

    public void setCodigoSeleccionado(String codigoSeleccionado) {
        this.codigoSeleccionado = codigoSeleccionado;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        No_Modificar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        descripcionCheckbox = new javax.swing.JCheckBox();
        unidadesCheckbox = new javax.swing.JCheckBox();
        precioCheckbox = new javax.swing.JCheckBox();
        nombreCheckbox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Precio_modificado = new javax.swing.JTextField();
        Descripcion_modificada = new javax.swing.JTextField();
        Nombre_modificado = new javax.swing.JTextField();
        Unidades_modificadas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(430, 180));

        No_Modificar.setText("Salir");
        No_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_ModificarActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        descripcionCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionCheckboxActionPerformed(evt);
            }
        });

        unidadesCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadesCheckboxActionPerformed(evt);
            }
        });

        precioCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioCheckboxActionPerformed(evt);
            }
        });

        nombreCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCheckboxActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel6.setText("--------------------------------------");

        jLabel7.setText("--------------------------------------");

        jLabel8.setText("--------------------------------------");

        jLabel2.setText("No modificar");

        jLabel3.setText("Precio");

        jLabel4.setText("Unidades");

        jLabel5.setText("Descripción");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nombreCheckbox)
                                    .addComponent(unidadesCheckbox)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(No_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(81, 81, 81)
                                        .addComponent(descripcionCheckbox))
                                    .addComponent(precioCheckbox))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(Nombre_modificado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26))
                                            .addComponent(Descripcion_modificada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(Precio_modificado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(Unidades_modificadas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(67, 67, 67))))))
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(79, 79, 79))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreCheckbox)
                    .addComponent(Nombre_modificado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Precio_modificado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Unidades_modificadas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidadesCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Descripcion_modificada, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(No_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(descripcionCheckbox)
                        .addGap(38, 38, 38))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void No_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_ModificarActionPerformed
        this.setVisible(false);
        Eliminar_articulo_ c=new Eliminar_articulo_();
        c.setVisible(true);  
    }//GEN-LAST:event_No_ModificarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        try {
            // Obtener los valores de entrada
            Integer nuevasUnidades = null;
            Double nuevoPrecio = null;
            String nuevoNombre = null;
            String nuevaDescripcion = null;
            String cod = getCodigoSeleccionado();

            // Verificar si cada checkbox está seleccionado y actualizar los valores correspondientes
            if (!nombreBloqueado) {
                nuevoNombre = this.Nombre_modificado.getText();
                if (nuevoNombre == null || nuevoNombre.trim().isEmpty()) {
                    throw new IllegalArgumentException("El nombre del artículo no puede ser null o una cadena vacía");
                }
            }else {
                // Desactivar el campo y cambiar el color de fondo  
                nuevoNombre=getNombreSeleccionado();
                this.Nombre_modificado.setEnabled(false);
                this.Nombre_modificado.setBackground(Color.LIGHT_GRAY);
            }
            if (!unidadesBloqueadas) {
                nuevasUnidades = Integer.parseInt(this.Unidades_modificadas.getText());
                if (nuevasUnidades <= 0) {
                    throw new IllegalArgumentException("El valor de unidades debe ser mayor que cero");
                }
            }else {
                // Desactivar el campo y cambiar el color de fondo
                nuevasUnidades=getUnidadesSeleccionado();
                this.Unidades_modificadas.setEnabled(false);
                this.Unidades_modificadas.setBackground(Color.LIGHT_GRAY);
            }
            if (!precioBloqueado) {
                nuevoPrecio = Double.parseDouble(this.Precio_modificado.getText());
                if (nuevoPrecio <= 0) {
                    throw new IllegalArgumentException("El valor de precio debe ser mayor que cero");
                }
            }else {
                // Desactivar el campo y cambiar el color de fondo
                nuevoPrecio=getPrecioSeleccionado();
                this.Precio_modificado.setEnabled(false);
                this.Precio_modificado.setBackground(Color.LIGHT_GRAY);
            }
            if (!descripcionBloqueada) {
                nuevaDescripcion = this.Descripcion_modificada.getText();
                if (nuevaDescripcion == null) {
                    throw new IllegalArgumentException("La Descripción del artículo no puede ser null o una cadena vacía");
                }
            }else {
                // Desactivar el campo y cambiar el color de fondo
                nuevaDescripcion=getDescripcionSeleccionado();
                this.Descripcion_modificada.setEnabled(false);
                this.Descripcion_modificada.setBackground(Color.LIGHT_GRAY);
            }
             // Modificar el artículo
            articulo_modificado(nuevoNombre, nuevaDescripcion, cod, nuevasUnidades, nuevoPrecio);
            JOptionPane.showMessageDialog(this, "El artículo ha sido modificado con éxito.", "Modificación exitosa", JOptionPane.INFORMATION_MESSAGE);
            
            this.setVisible(false);
            Eliminar_articulo_ c=new Eliminar_articulo_();
            // Actualizar la tabla en la interfaz de usuario existente
            c.cargar_tabla();
            c.setVisible(true);
        } catch (NumberFormatException ex) {
            // Mostrar un mensaje de error al usuario
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de entrada", JOptionPane.ERROR_MESSAGE);
        }catch(IllegalArgumentException | NullPointerException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);    
        }                       
    }//GEN-LAST:event_ModificarActionPerformed

    private void descripcionCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionCheckboxActionPerformed
        descripcionBloqueada = this.descripcionCheckbox.isSelected();
        this.Descripcion_modificada.setEditable(!descripcionBloqueada);
        if(descripcionBloqueada){
            this.Descripcion_modificada.setBackground(new Color(240, 240, 240)); // Cambiar el color de fondo a gris claro
        }else{
            this.Descripcion_modificada.setBackground(Color.WHITE); // Volver al color de fondo por defecto
        }
    }//GEN-LAST:event_descripcionCheckboxActionPerformed

    private void unidadesCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadesCheckboxActionPerformed
       unidadesBloqueadas = this.unidadesCheckbox.isSelected();
        this.Unidades_modificadas.setEditable(!unidadesBloqueadas);
        if(unidadesBloqueadas){
            this.Unidades_modificadas.setBackground(new Color(240, 240, 240)); // Cambiar el color de fondo a gris claro
        }else{
            this.Unidades_modificadas.setBackground(Color.WHITE); // Volver al color de fondo por defecto
        }  
    }//GEN-LAST:event_unidadesCheckboxActionPerformed

    private void precioCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioCheckboxActionPerformed
       precioBloqueado = this.precioCheckbox.isSelected();
        this.Precio_modificado.setEditable(!precioBloqueado);
        if(precioBloqueado){
            this.Precio_modificado.setBackground(new Color(240, 240, 240)); // Cambiar el color de fondo a gris claro
        }else{
            this.Precio_modificado.setBackground(Color.WHITE); // Volver al color de fondo por defecto
        }
    }//GEN-LAST:event_precioCheckboxActionPerformed

    private void nombreCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCheckboxActionPerformed
        nombreBloqueado = this.nombreCheckbox.isSelected();
        this.Nombre_modificado.setEditable(!nombreBloqueado);
        if(nombreBloqueado){
            this.Nombre_modificado.setBackground(new Color(240, 240, 240)); // Cambiar el color de fondo a gris claro
        }else{
            this.Nombre_modificado.setBackground(Color.WHITE); // Volver al color de fondo por defecto
        }
    }//GEN-LAST:event_nombreCheckboxActionPerformed
    private void articulo_modificado(String Nombre, String Descripcion, String cod, int Unidades, double Precio) {
        try (Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventario?autoReconnect=true&useSSL=false", "root", "")) {
            String sentenciaSQL = "UPDATE articulo SET Nombre = ?, Descripcion = ?, Unidades = ?, Precio = ? WHERE Codigo = ?";
            try (PreparedStatement sentencia = conexion.prepareStatement(sentenciaSQL)) {
                sentencia.setString(1, Nombre);
                sentencia.setString(2, Descripcion);
                sentencia.setInt(3, Unidades);
                sentencia.setDouble(4, Precio);
                sentencia.setString(5, cod);
                int filasModificadas = sentencia.executeUpdate();
                System.out.println(filasModificadas);
            }
        } catch (SQLException e) {
            System.out.println("Error al modificar el registro: " + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_articulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Modificar_articulo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Descripcion_modificada;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton No_Modificar;
    public static javax.swing.JTextField Nombre_modificado;
    public static javax.swing.JTextField Precio_modificado;
    public static javax.swing.JTextField Unidades_modificadas;
    private javax.swing.JCheckBox descripcionCheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox nombreCheckbox;
    private javax.swing.JCheckBox precioCheckbox;
    private javax.swing.JCheckBox unidadesCheckbox;
    // End of variables declaration//GEN-END:variables
}